### PR TITLE
Fix firefox issue, add radius prop

### PR DESCRIPTION
**Pull request by carlosfiori**
This PR fixes Firefox's #8 problem when the dots are not displayed correctly, also add new props to set the radius of the dots.

### CODE REVIEW

**Comment by David-Desmaisons** [comment]
@carlosfiori Thanks for your PR.
I have a couple of question:
-Is this property supported cross-browser?
-If so then could you update the PR removing unecessary CSS?

**Comment by carlosfiori** [comment]
I was able to test these browsers and versions:
- IE11
- Microsoft Edge 40
- Firefox 50.0.2
- Firefox 58
- Chrome 55
- Chrome 63

I found css only in these two classes and had already removed:
- .treclass .nodetree circle
- .treeclass .node - inner circle

Do you remember more places where CSS is unusable?

**Comment by carlosfiori** [comment]
@David-Desmaisons Can you review this PR?

**Comment by David-Desmaisons** [comment]
Thanks @carlosfiori

**Comment by David-Desmaisons** [comment]
Thanks for your contribution @carlosfiori, the change is available in version 3.5.0

**Pull request merged**
